version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-swift
    environment:
      POSTGRES_DB: swift_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: swift-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/swift_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: passwd
      SWIFT_DATA_FILE_PATH: /data/swiftCodes.xlsx
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
