version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-swift
    environment:
      POSTGRES_DB: swift_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  app:
#    build: .
#    container_name: swift-api
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_NAME: swift_db
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

volumes:
  postgres_data:
